name: "build"
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'

jobs:
  publish-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-22.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: 22
    - name: install Rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.84.0
    - name: install dependencies (ubuntu only)
      if: matrix.platform == 'ubuntu-22.04'
      run: >-
        sudo apt-get update &&
        sudo apt-get install -y
        libgtk-3-dev
        webkit2gtk-4.0
        libwebkit2gtk-4.1-dev
        libappindicator3-dev
        librsvg2-dev
        patchelf
        libsoup2.4-dev
        libjavascriptcoregtk-4.1-dev
        libsoup-3.0-dev
    - name: install app dependencies and build it
      run: yarn && yarn build
    - uses: tauri-apps/tauri-action@v0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
        TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
      with:
        tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
        releaseName: "OwnServer Client GUI v__VERSION__"
        releaseBody: "See the assets to download this version and install."
        releaseDraft: true
        prerelease: false
